print("****calculates the BMI through Metric Formula****")
h = float(input("enter the height (in meters) = "))
w = float(input("enter the weight (in kilograms) = "))
bmi = w / (h ** 2)
print ("BMI is = ",round(bmi,2) )